
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/teaglebuilt/netops-tool
  tag: ""
  pullPolicy: IfNotPresent
imagePullSecrets: []

iface: "en0"

priorityClassName: ""
extraEnv: []
nodeSelector: {}

tolerations:
  - operator: Exists
capabilities:
  - BPF
  - PERFMON
  - NET_ADMIN
  - SYS_ADMIN
seccompProfile:
  type: RuntimeDefault
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

metrics:
  port: 9101
  hostPort: 9101
  scrapeAnnotations: true

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podLabels: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  enabled: true
  initialDelaySeconds: 2
  periodSeconds: 5
