{{- if .Values.podSecurity.manageNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "netops.labels" . | nindent 4 }}
    {{- with .Values.podSecurity.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
